# DB Connection properties

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/crm_tracker?useSSL=false"
    username: "${DB_USER}"
    password: "${DB_PASS}"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect


pool:
  minSize: "5"
  maxSize: "20"
  maxIdleTime: "30000"

# Hibernate Factory properties

factory:
  scanPath: "info.esuarez.springwebcustomertracker.entity"
