# DB Connection properties

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/crm_tracker?useSSL=false"
    username: "${DB_USER}"
    password: "${DB_PASS}"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

